== Modules

[ditaa,align=center]
....

                       /------------+
                       |            |
                       |  Columbus  |
                       |            |
                       +------+-----/
                              |
                              |
                              |
                              v
        +-------------------------------------------+
        |                                           |
        |                  KAFKA                    |
        |                                           |
        +------------+---------------+--------------+
                     |               | ^
                     |               | |
                     |               | |
                     v               v |
                /-----------+   /------+----+
                |           |   |           |
                |  Galileo  |   |   Soho    |
                |           |   |  (Spark)  |
                |           |   |           |
                +-----------/   +-----------/


....


=== Columbus

`Columbus` module was built to discover new data. At the moment it feeds
Kafka with data coming from Twitter but in the future it could get
data from from anywhere.

It's accessible through HTTP thanks to http://sparkjava.com[SparkJava]
(Not be confused with Apache Spark). At the moment you can only:

- `Add` a new twitter hashtag stream to be stored in Kafka
- `Stop` a given hashtag stream feed

=== Galileo

`Galileo` is aimed to be module to expose all data gathered from
`columbus` and `soho`.

It is a http://ratpack.io[Ratpack] application that exposes several
`REST` and `SSE` endpoints in order to expose data analyzed by `soho`
or "real-time" data generated by `columbus`.

=== Soho

`Soho` is dedicated entirely to Apache Spark. It has several tasks that
analyze data coming from Kafka and stores results in Kafka or any
other support (database, text files...)

Tasks are written in http://scala-lang.org[Scala]. The main reason is
because I wanted to practising this language and also because there's
lot of documentation written in Scala.
